%% PCB_Show_ConfusionMatrix
% This function shows a grid of BIC scores for each model compared against
% datasets generated by each model on a given date for a given task.
% this only works when simulated data and model fit are run on same date
function PCB_Show_ConfusionMatrix(date,task, order)

if strcmp(task, '3fish')
    group_names = {'BID4'; 'BI1';'H1';'RLKF2';'RL1'};
else
    group_names = {'BID4'; 'BI1';'H1';'RLKF1';'RL1'};
end

if strcmp(order, 'reverse')
    y_names = flip(group_names);
else
    y_names = (group_names);
end
% 2025-03-25: Altered to show % subjects with winning model

% 2025-10-10: Altered to show AIC, not BIC

% BIC will store the average aic scores for each model (rows)
% on each dataset (columns)
BIC = zeros(5,5);

% this is the % of subjects with the best model for each model
BEST_BIC = zeros(5,5);
% for each group's dataset, get model BIC scores
for iG = 1:5
    group = [group_names{iG},'_sim100'];
    % get BIC scores for dataset generated by each group
    % [RL1, RLKF1, H1, BI1, BID4]
    [~, bic] = PCB_Get_BIC(date, task, group, order, 3); % bic is actually aic
    best_bic = zeros(length(bic),5);
    for iS = 1:length(bic)
        best_bic(iS,:) = bic(iS,:) == min(bic(iS,:));
    end
    BEST_BIC(:,iG) = mean(best_bic);
    BIC(:,iG) = mean(bic);
end

%% generate heatmap
figure;
if strcmp(task, '3slot')
    h = heatmap(group_names, y_names, BEST_BIC, ...
        'CellLabelFormat','%.2f', ...
        'Colormap', pink , ... % use pink for slot
        'ColorbarVisible','on');
else
    h = heatmap(group_names, y_names, BEST_BIC, ...
        'CellLabelFormat','%.2f', ...
        'Colormap', bone , ... % use bone for fish
        'ColorbarVisible','on');
end
h.ColorLimits = [0 1];
% Axis labels
h.Title = '% of subjects with Best AIC Score';
h.XLabel = 'Data-Generating Model';
h.YLabel = 'Fitting Model';



